### ISSUE TITLE
Look into IDX

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/yelloweye-inside#13]
numerator/denominator?

**Comment by seananderson** [comment]
I think it looks right:

```r
  # Stepwise fill in NAs with last available value:
  temp_Ind <- stepwise_NAs(Data@Ind[x, ])

  delta_ind_y <- temp_Ind[this_year] / temp_Ind[this_year - year_ref] - 1
  catch_rec <- Data@MPrec[x]

  if (delta_ind_y <= delta_min) {
    TAC <- tac_floor
  }
  if (delta_min < delta_ind_y && delta_ind_y <= delta_max) {
    TAC <- (1 + delta_ind_y) * catch_rec
  }
  if (delta_ind_y > delta_max) {
    TAC <- (1 + delta_max) * catch_rec
  }

```

**Comment by seananderson** [comment]
Oh, why is there a `-1` on the second code line? Shouldn't that be inside the brackets or not there at all depending on inclusive counting?

**Comment by robynforrest** [comment]
I think we can close this now?

**Comment by seananderson** [comment]
Perhaps. Although we now know that IDX is a bit silly for this stock and is prone to ratchets and weird "floor" behaviour. Dropping things here as an archive:

![image (7)](https://user-images.githubusercontent.com/19349/77197564-a6912e00-6aa2-11ea-806d-9b5638a6bc08.png)

The blue dots represent hitting the maximal increase, the red dots represent hitting the maximal decrease the grey dots are in the middle taking the recommendation. Take a look at the red dot in the 70s -- the index goes low so the MP sets the TAC to TAC_floor.

It's coded correctly but is just not set up in a smart way for (1) an index with this much variability from year to year (but most probably have that) and (2) being this close to TAC_floor that sometimes it becomes a ceiling when you want it to be a floor!

And the asymmetric HCR keeps driving it lower. It takes the decreases at face value and never lets it increase the full amount.

Either they (OYE) didn't code it the way they described, had the same problem but the figures don't highlight it, or they were lucky and never got near the floor.

Maybe they had an additional meta rule that set the floor to the floor regardless but didn't mention that. In general though, you can't be hitting the high and low HCR limits too frequently or you are going to get this ratchet. And if you relax those delta_max and delta_min then you are going to get very variable TACs. I think for an index that variable from year to year you just need to look at some longer trend than last year to this year. Or really relax delta_max and delta_min and really crank up the smoothing parameter.

Widening the area of the ramp allows it to track the index more closely.

Still some stuff I can't understand:

I've made it so that it never hits the ramp edges. This is with no smoothing. Makes sense.
![image (5)](https://user-images.githubusercontent.com/19349/77197416-5dd97500-6aa2-11ea-9e3a-f8e90bda3c50.png)

But here is with lots of smoothing (taking 20% of new recommendation)
![image (6)](https://user-images.githubusercontent.com/19349/77197454-72b60880-6aa2-11ea-8aa5-b72899f7801d.png)

why does it ratchet up? 

I think this is the type of thing I was thinking about when thinking that target MPs would be less likely to have pathological behaviour because they have an anchor. When you're only looking at the last year it's easy for a slightly biased rule to create chaos

**Comment by seananderson** [comment]
I think our options are to:

1. Drop IDX with a bit of an explanation
2. Keep IDX but mention that it's basically nonsensical here. Might make for an interesting discussion.
3. Make it slightly more sensible by relaxing the upper and lower bounds on the ramp, adding a final actual TAC_floor that always gets enacted, and considering a more smoothed version (but see the possibly bizarre behaviour above with too much smoothing)

If we do 3, it shouldn't be too hard to just rerun IDX and stitch it into the current results.

**Comment by danahaggarty** [comment]
Hey there, I think that 2 might make sense. I would like this discussion to be captured as it relates to OYE as well. From learning about this framework, it is interesting to show a proceedure that doesn't work. Some things that might be different about the OYE vs. this is that 1. the index is much better (lower cvs) and less variable temporally. There are still spatial differences that would swing the index if the 2 surveys were stitched together, but we didn't do this-we divided the study area instead to correspond (more or less, although part of the "N" used a subset of the S-index area). 2. The floor was a true floor that was always enacted, i think.

**Comment by robynforrest** [comment]
I think this one is a case for "tuning" MPs so they don't have pathological behaviour. In this case I think delta_max is too small (0.25), essentially only letting the TAC increase by 25%. When it gets trapped in a low place due to a large drop in one year (around year 35 in the above), it can't get out unless there is a large jump. 

I think we need to be careful of just saying it didn't work (and why). In our case people will just ask why we didn't set the ramp wider to stop these traps happening, which evidently they did in most replicates. 

So my vote would be (3) with an explanation of what can happen with low delta_max and a variable index.

**Comment by seananderson** [comment]
I think there is an argument for long-lived species with high observation error on an index that any MP that relies on comparing 2 single index years to each other isn't going to be appropriate.

If we really want to make IDX seem reasonable, we might want to make it more like Iratio and use 2 + 3 years or 5 + 5. If you do that, IDX becomes Iratio with a ceiling and floor. As we've seen, you can't be hitting that ceiling and floor very often or you end up with a ratcheting MP (unless the ceiling and floor are balanced).

As it's implemented now, exactly as originally described, it's truly nonsensical since it's happy to slowly shut the fishery down only to be rescued by the floor that serves as a ceiling.

**Comment by robynforrest** [comment]
LOL, yes that's pretty hilarious behaviour
