### ISSUE TITLE
Reference oddity

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/yelloweye-inside#19]
This should not hold up submitting the paper but it is curious that the YE doc (for me) renders anderson2020gfmp as Anderson et al 2020**d**, even though it is the first Anderson et al reference (Line 6 of the introduction)

**Comment by seananderson** [comment]
If it's anything like BibTeX, the default order of references with the same citation name and year get sorted alphabetically according to how the bibliography entries are written. I'm not sure if there is an easy way to fix this with Pandoc. I can take a look, but yeah, let's not hold this up for that. Worst-case, in the end, we can just hand edit the .tex file and recompile it.

**Comment by seananderson** [comment]
Looks like we need to fix this in the .csl file in csasdown. Let's not worry about it for now. I filed an issue:
https://github.com/pbs-assess/csasdown/issues/124

**Comment by seananderson** [comment]
Chris figured this out quickly on the weekend: https://github.com/pbs-assess/csasdown/commit/556c1a2f009cc90d2bf7e6b7b8755d4b3e0a58ab

You'll need to update your csasdown installation.
