### ISSUE TITLE
Check write up of AADC in 02-objectives.Rmd

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/yelloweye-inside#20]
The write up of AADC includes years 2021-2029 

$$
\textrm{AADC}_\textrm{2020-2029} = \dfrac{1}{8}\sum_{y=2021}^{2029} \mid C_y - C_{y-1} \mid.
$$

If the summation includes the first year, as implied by the notation, then n=9 not 8.

**Comment by seananderson** [comment]
It's used here:
https://github.com/pbs-assess/yelloweye-inside/blob/b065db56c7933fc92e77ebaec971c7720bdfc01d/mse/08-plot-mse.R#L28

```r
`ST AADC` <- gfdlm::pm_factory("AADC", ref_aadc, c(1, 10))
```

And the function is defined as `function(x) mean(abs(diff(x)))`

Year 1 is 2020, right? So the function is applied to years 2020:2029. The diff means we need to start one year later. So, yes:

```tex
\textrm{AADC}\textrm{2020-2029} = \dfrac{1}{9}\sum{y=2021}^{2029} \mid C_y - C_{y-1} \mid.
```

I'll fix that now.
