### ISSUE TITLE
Improve wording of Objective 6 description

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/yelloweye-inside#22]
From Lindsay Gardner:
Basically, I think this sentence on Pg 8 could change from:
We adjusted the milestone to reflect the assumption that, once the stock is rebuilt (i.e. no longer in the critical zone), the milestone would no longer be required.
To:
We adjusted the milestone to reflect the assumption that, once the stock is no longer in the critical zone, the milestone would no longer be required.
OR:
We adjusted the milestone to reflect the assumption that, once the stock is above the LRP, the milestone would no longer be required.

**Comment by danahaggarty** [comment]
done
