### ISSUE TITLE
Update cosewic description of Metric A and Metric E (equations)

### ISSUE THREAD

**Issue by MJBresch** [pbs-assess/yelloweye-inside#26]

**Comment by MJBresch** [comment]
Made a small change. Not sure what they meant by the needing the equation for Metric E. The equation is in the text already. 
https://github.com/pbs-assess/yelloweye-inside/commit/6ca3683d96dc952e9493f7b883165c2a32dd455b

**Comment by danahaggarty** [comment]
looks good!
