### ISSUE TITLE
Change name of "Upweight dogfish survey" to "Base" ?

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/yelloweye-inside#3]
Wondering if we should call OM (1) something like "Base" rather than "Upweight dogfish survey"? Upweight dogfish survey awkwardly implies that it is a modification of another OM ... which it was originally but we trashed that OM. Then we can spend more time describing its settings and sources. It will be much easier to cite when describing the other OMs. Is this easy to do after the fact? We just need to change the name in the csv file (and the scenario names in the code)?

**Comment by seananderson** [comment]
done
