### ISSUE TITLE
Translate SAR Figures-Figure 2. 

### ISSUE THREAD

**Issue by danahaggarty** [pbs-assess/yelloweye-inside#32]
Figure 2. The steps of the MSE process following Punt et al. (2016) as implemented in DLMtool. Copied from Anderson et al. (2020) and adapted from Carruthers and Hordyk (2018a).

**Comment by seananderson** [comment]
Done https://github.com/pbs-assess/yelloweye-inside/commit/db44e24878b26cb799668745381862a891410948
