### ISSUE TITLE
Translate SAR Figures-Figure 3, 4, 5, 6, 7, 8

### ISSUE THREAD

**Issue by danahaggarty** [pbs-assess/yelloweye-inside#33]
All from GF-DLM so you should be able to do these all together pretty easily.

**Comment by seananderson** [comment]
Done here https://github.com/pbs-assess/yelloweye-inside/commit/a896b7127f8d29dade5578bb10caf391baaffe8a plus the latest version of gfdlm and rosettafish

I can send you my copies if you ask.
