### ISSUE TITLE
Translate SAR Figures-Figure A.1

### ISSUE THREAD

**Issue by danahaggarty** [pbs-assess/yelloweye-inside#34]
Figure A.1. SRA model fits to the HBLL, Dogfish, and three commercial CPUE relative indices. Panels from left to right represent OM scenarios. Thin lines represent individual SRA model fits across stochastic draws from the various OM parameters. Dots represent index mean and line segments represent 2 times the standard errors as entered into the SRA models.
Perhaps Robyn, you can do this one with me?

**Comment by seananderson** [comment]
I think I accidentally translated this one along with a ton of other figures in this commit https://github.com/pbs-assess/yelloweye-inside/commit/577ad0dd657ecd3ed34c4e0f6609e3d4ad45e5f0

There's still 1/3 of that file to go and I'm burning out for now.

**Comment by danahaggarty** [comment]
Well, we might have all the SAR figs done then! Awesome! This will make Ann very happy!

**Comment by robynforrest** [comment]
Haven't forgotten this. DH and I will revisit next week

**Comment by seananderson** [comment]
I believe this is all done. I'll close for now.
