### ISSUE TITLE
Please check 03-om.Rmd

### ISSUE THREAD

**Issue by robynforrest** [pbs-assess/yelloweye-inside#5]
Quang and Sean, please check 03-om.Rmd.

Lots of TODOs, questions, plus the fact I haven't proof-read it.
Plus getting a weird error:
"Cannot find the file(s): "C:/GitHub/yelloweye-inside/mse/figures/HBLL_age_comp_updog_fixsel.png"
I can't find that call anywhere in the file or the project. Let me know if you get it.

**Comment by seananderson** [comment]
HBLL_age_comp_updog_fixsel.png is in conditioning; try trashing the cache? knitr-cache-pdf
https://github.com/pbs-assess/yelloweye-inside/blob/169b9d6e9b9a982a698bec1a1f4fd3ac8c104dd2/report/03-om.Rmd#L266

**Comment by seananderson** [comment]
And I just fixed lots of things. Get the newest figs.

**Comment by robynforrest** [comment]
Yep, the include_graphics call out refers to the correct location, can't find anywhere it is looking for figures/HBLL_age_comp_updog_fixsel.png. It knits anyway, will look at it again later.

**Comment by seananderson** [comment]
Almost certainly a cache problem then
