### ISSUE TITLE
Create figures for catch appendix

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/yelloweye-inside#7]
E.g., see here:
https://github.com/pbs-assess/yelloweye-inside/blob/8360f1e771a1202e2f92e263bb02a98686722a94/report/10-app-catch-data.Rmd#L49-L61

My preference would be to just have the figures and not the tables, but I could be overruled on that.

The data itself will be available in the .csv files.

**Comment by robynforrest** [comment]
Table 5-6 figure (PFMA) ? No. What are NAs? No data. Two hyphens

Add rec catch to catch fig
