### ISSUE TITLE
Refine description of catch data

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/yelloweye-inside#8]
> Regarding the catch reconstruction, seems that we did double the 1986-2005 commercial catch in all OM Scenarios except Low catch, as expected. See discussion on the inside-yelloweye Slack thread.
 
> However, the catch data appendix  (now file 10-app-catch-data.Rmd) said that we used nominal catch data from 1986-2005. The captions for Table commcatch and Figure commcatch2 also say they show the nominal catch from 1986-2005.
 
> Given that all OMs except Low catch did use the doubled catch, I have removed the text about using nominal 1986-2005 catch from the comm catch description in the appendix and moved it into 03-om.Rmd under the Low catch description. Not sure what to do about the Table and Figure, seems we should be showing the doubled catches if that is what we used in all OMs, with a note that we used the nominal catches in the Low catch scenario.

**Comment by MJBresch** [comment]
I worked on this a bit yesterday. It is challenging to clearly describe but take a look and let me know if it is still unclear. I didn't change anything in the table b/c I wasn't sure if we were going to keep it, or switch to a figure.

**Comment by MJBresch** [comment]
I think this issue is resolved. If anyone is still not happy with the description feel free to edit.
